#pragma once
#ifndef ANT_H
#define ANT_H

#define UINT unsigned int
#define NULL 0


enum ANTGUI_EVENT
{
	ANTGUI_EVENT_KEYDOWN,
	ANTGUI_EVENT_LBUTTONDOWN,
	ANTGUI_EVENT_LBUTTONUP,
	ANTGUI_EVENT_MOUSEMOVE,
	ANTGUI_EVENT_KEYUP,
	ANTGUI_EVENT_QUIT,
	ANTGUI_EVENT_CHAR,
	ANTGUI_EVENT_KEY_UP,
	ANTGUI_EVENT_KEY_DOWN,
	ANTGUI_EVENT_KEY_LEFT,
	ANTGUI_EVENT_KEY_RIGHT,
	ANTGUI_EVENT_KEY_BACK,
	ANTGUI_EVENT_KEY_ESCAPE,
	ANTGUI_EVENT_KEY_RETURN,
	ANTGUI_EVENT_KEY_SPACE,
	ANTGUI_EVENT_KEY_SHIFT,
};

#endif
